"""Added type column to sports model

Revision ID: 9e194ed2a4a9
Revises: 0e3f6220a033
Create Date: 2025-01-19 00:22:16.846759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e194ed2a4a9'
down_revision = '0e3f6220a033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
